Fix API reference to Writer->setFeedLinks()
zendframework/zend-feed pull request #43
Opened 2017-06-18 14:33 UTC by elazar

setFeedLink() is the correct method

2017-06-19 20:25 UTC, froschdesign requested changes

2017-06-19 20:25 UTC, froschdesign commented on doc/book/writer.md
> -`setFeedLinks()` | Add a link to an XML feed, whether it is to the feed being generated, or an alternate URI pointing to the same feed but in a different format. At a minimum, it is recommended to in
@elazar 
Can you also check the [table for `Zend\Feed\Writer\Entry`](https://github.com/zendframework/zend-feed/blob/master/doc/book/writer.md#setting-entry-data-points). There is the same wrong method included. Thanks!

2017-06-20 00:52 UTC, elazar commented on doc/book/writer.md
> -`setFeedLinks()` | Add a link to an XML feed, whether it is to the feed being generated, or an alternate URI pointing to the same feed but in a different format. At a minimum, it is recommended to in
Done!

2017-06-20 03:56 UTC, froschdesign approved these changes

2017-11-01 19:21 UTC, merged

2017-11-01 19:22 UTC, weierophinney commented
Thanks, @elazar!