Added Reader/Writer methods and tests for <itunes:title> on entry level
zendframework/zend-feed pull request #96
Opened 2019-03-01 10:42 UTC by podcasthosting

There is a (new) field in the Itunes podcast spec for the episode title. 
See https://help.apple.com/itc/podcasts_connect/#/itcb54353390 > **Episode descriptions** > <itunes:title>

The pull requests adds the missing methods for reading and writing a feed and the tests.

2019-03-01 10:57 UTC, froschdesign commented
@podcasthosting 
Do you know if there is finally a file for the DTD?

2019-03-01 11:26 UTC, froschdesign commented on src/Reader/Extension/Podcast/Entry.php
> +    public function getTitle()
Mmmmh, a test class for the entire `Zend\Feed\Reader\Extension\Podcast\Entry` is missing.

2019-03-01 11:38 UTC, froschdesign commented
@podcasthosting 
Thanks for your contribution, I will check later in the day.

2019-03-02 07:32 UTC, froschdesign commented
@OpenHaus 
Can you answer my previous question?

2019-03-02 07:37 UTC, froschdesign approved these changes
Looks good to me. 👍 

(The coding standard is a separate topic and is related to the whole component.)

2019-03-02 08:10 UTC, froschdesign requested changes
@podcasthosting @OpenHaus 
Please use the `develop` branch for new features. Thanks!

Compare with: https://github.com/zendframework/zend-feed/blob/master/docs/PULL_REQUEST_TEMPLATE.md

2019-03-04 08:16 UTC, podcasthosting commented
> @podcasthosting
> Do you know if there is finally a file for the DTD?

It does not seem so. The uri referencing the DTD [in the specs](https://help.apple.com/itc/podcasts_connect/#/itcb54353390) is not reachable:

`<rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" version="2.0">`

I have no further information.

2019-03-04 08:26 UTC, froschdesign commented
@podcasthosting 
> I have no further information.

Okay, thanks for the feedback anyway. 👍 
(I was hoping we could simplify the unit tests.)

2019-03-05 19:55 UTC, weierophinney commented
Thanks, @podcasthosting! I rebased your branch against develop, and merged against develop for the upcoming 2.12.0 release.

2019-03-05 19:55 UTC, closed without merging